controller_type: OSC_POSITION

is_delta: true

traj_interpolator_cfg:
  traj_interpolator_type: LINEAR_POSE
  time_fraction: 0.3

Kp:
  translation: [230.0, 230.0, 230.0]
  rotation: 280.0

action_scale:
  translation: 0.0375
  rotation: 1.0

residual_mass_vec:  [0.0, 0.0, 0.0, 0.0, 0.3, 0.9, 1.0]

state_estimator_cfg:
  is_estimation: true
  state_estimator_type: EXPONENTIAL_SMOOTHING
  alpha_q: 0.9
  alpha_dq: 0.9
  alpha_eef: 1.0
  alpha_eef_vel: 1.0
