controller_type: OSC_POSITION

is_delta: true

traj_interpolator_cfg:
  traj_interpolator_type: LINEAR_POSE
  time_fraction: 0.5

Kp:
  translation: [230.0, 230.0, 230.0]
  rotation: 290.0

action_scale:
  translation: 0.025
  rotation: 1.0

#  [0.1, 0.2, 0.25, 0.30, 0.35, 1.0, 1.1]
residual_mass_vec: [0.15, 0.35, 0.35, 0.35, 0.45, 0.9, 1.1]

state_estimator_cfg:
  is_estimation: true
  state_estimator_type: EXPONENTIAL_SMOOTHING
  alpha_q: 0.9
  alpha_dq: 0.9
  alpha_eef: 1.0
  alpha_eef_vel: 1.0
